
#server:
#  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
jwt:
  expiry: 3600000
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"